version: '3.2'

services:
  devenv:
    image: srakshit/devenv
    volumes:
      - ~/.ssh:/home/docker/.ssh:ro
      - ./media/sf_git:/workspace
    tty: true

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
