version: '3.2'

services:
  devenv:
    image: srakshit/devenv
    volumes:
      - ~/.ssh:/home/docker/.ssh:ro
      - /media/sf_git:/workspace
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
